# Generated by Django 2.0.4 on 2018-07-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Cuisne', models.CharField(max_length=50)),
                ('Dresscode', models.CharField(max_length=30)),
                ('Opening_Time', models.TimeField()),
                ('Closing_Time', models.TimeField()),
                ('Kids_allowed', models.CharField(max_length=8)),
                ('Walk_in_allowed', models.CharField(max_length=8)),
                ('Comments', models.TextField(max_length=200)),
            ],
        ),
    ]
