# Generated by Django 2.0.4 on 2018-07-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Closing_Time',
            new_name='closing_time',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Cuisne',
            new_name='cuisine',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Dresscode',
            new_name='dresscode',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Kids_allowed',
            new_name='kids_allowed',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Opening_Time',
            new_name='opening_time',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Walk_in_allowed',
            new_name='walk_in_allowed',
        ),
    ]
